# Generated by Django 5.2.13 on 2026-05-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_project_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
            },
        ),
        migrations.AlterField(
            model_name="contact",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
