# Generated by Django 5.2.13 on 2026-09-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_contact_message_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="desc_code_en",
            field=models.TextField(
                blank=True,
                help_text="Short kodzillin'-style blurb for /code/ (EN). Falls back to desc_en if empty.",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="desc_code_pl",
            field=models.TextField(
                blank=True,
                help_text="Short kodzillin'-style blurb for /code/ (PL). Falls back to desc_pl if empty.",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="desc_en",
            field=models.TextField(
                blank=True, help_text="Full CV description for / (recruiter landing)."
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="desc_pl",
            field=models.TextField(
                blank=True, help_text="Full CV description for / (recruiter landing)."
            ),
        ),
    ]
