# Generated by Django 5.2.14 on 2026-07-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instagrampost",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="instagrampost",
            name="image_url",
        ),
        migrations.AddField(
            model_name="instagrampost",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="instagrampost",
            name="permalink",
            field=models.URLField(
                blank=True,
                help_text="Optional link to the original Instagram post (shown as a small IG icon).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="instagrampost",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instagram_posts",
                to="gallery.category",
            ),
        ),
        migrations.CreateModel(
            name="InstagramPostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="instagram")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="gallery.instagrampost",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
