# Generated by Django 5.2.14 on 2026-07-18 17:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_instagrampost_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramPostMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="instagram"),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Upload a reel here instead of an image. Leave the image field empty.",
                        null=True,
                        upload_to="instagram/reels",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "mov", "webm"]
                            )
                        ],
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="gallery.instagrampost",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.DeleteModel(
            name="InstagramPostImage",
        ),
    ]
