# Generated by Django 5.2.14 on 2026-07-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_instagrampostmedia_delete_instagrampostimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order", "title"]},
        ),
        migrations.AddField(
            model_name="category",
            name="is_instagram_category",
            field=models.BooleanField(
                default=False,
                help_text="Zaznacz, jeśli ta kategoria ma pokazywać posty w stylu Instagrama (ręcznie dodawane zdjęcia/rolki) zamiast zwykłej siatki galerii.",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Kolejność wyświetlania kategorii (mniejsza liczba = wyżej na liście).",
            ),
        ),
    ]
