# Generated by Django 5.2.14 on 2026-07-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_instagram_category",
        ),
    ]
