# Generated by Django 5.2.14 on 2026-09-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_remove_category_is_instagram_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.AddConstraint(
            model_name="instagrampostmedia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("image__gt", ""),
                        models.Q(
                            ("video", ""), ("video__isnull", True), _connector="OR"
                        ),
                    ),
                    models.Q(
                        models.Q(
                            ("image", ""), ("image__isnull", True), _connector="OR"
                        ),
                        ("video__gt", ""),
                    ),
                    _connector="OR",
                ),
                name="instagram_media_xor_image_video",
            ),
        ),
    ]
