# Generated by Django 5.2.17 on 2026-09-29 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_pl", models.TextField(verbose_name="Question (PL)")),
                ("text_en", models.TextField(verbose_name="Question (EN)")),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name_pl", models.CharField(max_length=80, verbose_name="Name (PL)")),
                ("name_en", models.CharField(max_length=80, verbose_name="Name (EN)")),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("uderzenia", "Uderzenia"),
                            ("chwyty", "Chwyty"),
                            ("mieszane", "Mieszane"),
                            ("bron", "Broń"),
                        ],
                        max_length=20,
                    ),
                ),
                ("joke_pl", models.CharField(max_length=240, verbose_name="Joke (PL)")),
                ("joke_en", models.CharField(max_length=240, verbose_name="Joke (EN)")),
                ("summary_pl", models.TextField(verbose_name="Summary (PL)")),
                ("summary_en", models.TextField(verbose_name="Summary (EN)")),
                (
                    "history_pl",
                    models.TextField(blank=True, verbose_name="History (PL)"),
                ),
                (
                    "history_en",
                    models.TextField(blank=True, verbose_name="History (EN)"),
                ),
                (
                    "practice_pl",
                    models.TextField(blank=True, verbose_name="How it is fought (PL)"),
                ),
                (
                    "practice_en",
                    models.TextField(blank=True, verbose_name="How it is fought (EN)"),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Style",
                "verbose_name_plural": "Styles",
                "ordering": ["sort_order", "name_pl"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=200)),
                ("title", models.CharField(max_length=300)),
                ("url", models.URLField(blank=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="walczak.style",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_pl",
                    models.CharField(max_length=300, verbose_name="Answer (PL)"),
                ),
                (
                    "text_en",
                    models.CharField(max_length=300, verbose_name="Answer (EN)"),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("points", models.PositiveSmallIntegerField(default=1)),
                ("extra_points", models.PositiveSmallIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="walczak.question",
                    ),
                ),
                (
                    "extra_style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extra_choices",
                        to="walczak.style",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="choices",
                        to="walczak.style",
                    ),
                ),
            ],
            options={
                "verbose_name": "Choice",
                "verbose_name_plural": "Choices",
                "ordering": ["sort_order", "pk"],
            },
        ),
    ]
