# Generated by Django 5.2.17 on 2026-09-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walczak", "0003_expand_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="quality",
            field=models.CharField(
                choices=[
                    ("institutional", "Institutional"),
                    ("academic", "Academic"),
                    ("reputable_reference", "Reputable reference"),
                    ("secondary", "Secondary"),
                    ("discovery_only", "Discovery only"),
                ],
                default="secondary",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="role",
            field=models.CharField(
                choices=[
                    ("definition", "Definition"),
                    ("history", "History"),
                    ("rules", "Rules"),
                    ("current_practice", "Current practice"),
                    ("heritage", "Heritage"),
                    ("academic", "Academic"),
                    ("psychology", "Psychology"),
                    ("image", "Image"),
                    ("discovery", "Discovery"),
                ],
                default="definition",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="sample_size",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="study",
            name="study_type",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="study",
            name="year",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="style",
            name="is_umbrella",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="style",
            name="matcher_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
