# Generated by Django 5.2.14 on 2026-09-05 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tonguetwister", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="last_login_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="login_streak",
        ),
        migrations.AddConstraint(
            model_name="userprofilearticulator",
            constraint=models.UniqueConstraint(
                fields=("user", "articulator"), name="uniq_user_articulator"
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofileexercise",
            constraint=models.UniqueConstraint(
                fields=("user", "exercise"), name="uniq_user_exercise"
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofiletwister",
            constraint=models.UniqueConstraint(
                fields=("user", "twister"), name="uniq_user_twister"
            ),
        ),
    ]
