# Generated by Django 5.2.14 on 2026-06-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bies", "0003_alter_swieto_duchy_en_alter_swieto_duchy_pl_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="swieto",
            options={
                "ordering": ["kolejnosc", "tytul_pl"],
                "verbose_name": "Festival",
                "verbose_name_plural": "Festivals",
            },
        ),
        migrations.AlterModelOptions(
            name="zrodlobibliograficzne",
            options={
                "ordering": ["kolejnosc"],
                "verbose_name": "Bibliographic source",
                "verbose_name_plural": "Bibliographic sources",
            },
        ),
        migrations.AlterField(
            model_name="swieto",
            name="duchy_en",
            field=models.CharField(
                blank=True,
                help_text="E.g. 'Jaryło, Marzanna, Spring'. Comma-separated.",
                max_length=300,
                verbose_name="Spirits / deities (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="duchy_pl",
            field=models.CharField(
                blank=True,
                help_text="E.g. 'Jaryło, Marzanna, Wiosna'. Comma-separated.",
                max_length=300,
                verbose_name="Spirits / deities (PL)",
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="kolejnosc",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Ordering on list and position on the Wheel of the Year (1–12, ascending).",
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="kolo_kat",
            field=models.SmallIntegerField(
                default=0,
                help_text="Festival position on the circle. 0° = top (winter solstice), then clockwise. E.g. spring equinox ≈ 90°.",
                verbose_name="Wheel angle (degrees)",
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="kolo_kolor",
            field=models.CharField(
                default="#c4922a",
                help_text="Hex color, e.g. '#a3c47a' for spring, '#c4922a' for golden tones.",
                max_length=20,
                verbose_name="Wheel node color",
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="meta_opis_en",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Meta description (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="meta_opis_pl",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Meta description (PL)"
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="o_swiecie_en",
            field=models.TextField(blank=True, verbose_name="About (EN)"),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="o_swiecie_pl",
            field=models.TextField(blank=True, verbose_name="About (PL)"),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="obraz",
            field=models.ImageField(
                blank=True,
                help_text="Recommended format: PNG or JPG, min. 1200×800 px.",
                null=True,
                upload_to="bies/swieta/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="obrzedy_en",
            field=models.TextField(blank=True, verbose_name="Rituals (EN)"),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="obrzedy_pl",
            field=models.TextField(blank=True, verbose_name="Rituals (PL)"),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="podtytul_en",
            field=models.CharField(
                blank=True, max_length=220, verbose_name="Subtitle (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="podtytul_pl",
            field=models.CharField(
                blank=True, max_length=220, verbose_name="Subtitle (PL)"
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="slug",
            field=models.SlugField(
                help_text="URL part, e.g. 'gaik', 'jare-gody'. Auto-filled if empty.",
                max_length=80,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="symbolika_en",
            field=models.TextField(blank=True, verbose_name="Symbolism (EN)"),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="symbolika_pl",
            field=models.TextField(blank=True, verbose_name="Symbolism (PL)"),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="tytul_en",
            field=models.CharField(max_length=120, verbose_name="Title (EN)"),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="tytul_pl",
            field=models.CharField(max_length=120, verbose_name="Title (PL)"),
        ),
        migrations.AlterField(
            model_name="zrodlobibliograficzne",
            name="autor",
            field=models.CharField(blank=True, max_length=200, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="zrodlobibliograficzne",
            name="swieto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zrodla",
                to="bies.swieto",
                verbose_name="Festival",
            ),
        ),
        migrations.AlterField(
            model_name="zrodlobibliograficzne",
            name="tytul",
            field=models.CharField(max_length=400, verbose_name="Work title"),
        ),
        migrations.AlterField(
            model_name="zrodlobibliograficzne",
            name="url",
            field=models.URLField(blank=True, verbose_name="Link (optional)"),
        ),
        migrations.AlterField(
            model_name="zrodlobibliograficzne",
            name="url_etykieta",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Link label"
            ),
        ),
        migrations.AlterField(
            model_name="zrodlobibliograficzne",
            name="wydawca_rok",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Publisher / year"
            ),
        ),
    ]
