# Generated by Django 5.2.14 on 2026-06-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bies", "0004_alter_swieto_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="swieto",
            name="dzien_roku",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Approximate calendar day of this festival (Jan 1 = 1, Dec 31 = 365). Used to auto-highlight the nearest feast on the Wheel of the Year. E.g. Noc Kupały ≈ Jun 23 → 174, Szczodre Gody ≈ Dec 21 → 355.",
                verbose_name="Day of year (1–365)",
            ),
        ),
    ]
