# Generated by Django 5.2.14 on 2026-06-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bies", "0005_swieto_dzien_roku"),
    ]

    operations = [
        migrations.AddField(
            model_name="swieto",
            name="wideo",
            field=models.FileField(
                blank=True,
                help_text="MP4, recommended max 10 MB. Used as card thumbnail and hero background.",
                null=True,
                upload_to="bies/swieta/video/",
                verbose_name="Video (MP4)",
            ),
        ),
    ]
