# Generated by Django 5.2.14 on 2026-07-07 08:30

import core.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bies", "0006_swieto_wideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="swieto",
            name="dzien_roku_koniec",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Only for festivals spanning a range of days, e.g. all of January = 1 to 31. Leave BLANK for ordinary single-day festivals — do not fill this in unless the festival really covers a whole period.",
                null=True,
                verbose_name="Day of year — end (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="dzien_roku",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Approximate calendar day of this festival (Jan 1 = 1, Dec 31 = 365). Used to auto-highlight the nearest feast on the Wheel of the Year. E.g. Noc Kupały ≈ Jun 23 → 174, Szczodre Gody ≈ Dec 21 → 355. If 'Day of year — end' below is set, this is the START of a range.",
                verbose_name="Day of year (1–365)",
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="obraz",
            field=models.ImageField(
                blank=True,
                help_text="Recommended format: PNG or JPG, min. 1200×800 px.",
                null=True,
                storage=core.storages_backends.get_bies_storage,
                upload_to="bies/swieta/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="wideo",
            field=models.FileField(
                blank=True,
                help_text="MP4, recommended max 10 MB. Used as card thumbnail and hero background.",
                null=True,
                storage=core.storages_backends.get_bies_storage,
                upload_to="bies/swieta/video/",
                verbose_name="Video (MP4)",
            ),
        ),
    ]
