# Generated by Django 5.2.14 on 2026-07-09 07:16

import core.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bies", "0007_swieto_dzien_roku_koniec_alter_swieto_dzien_roku_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swieto",
            name="duchy_en",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED fallback — see PL field.",
                max_length=300,
                verbose_name="Spirits / deities (EN) — legacy",
            ),
        ),
        migrations.AlterField(
            model_name="swieto",
            name="duchy_pl",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED fallback, comma-separated plain text. Prefer linking a proper 'Bostwo' record below instead — that gives a portrait, a storytelling description and a trivia box on the page.",
                max_length=300,
                verbose_name="Spirits / deities (PL) — legacy",
            ),
        ),
        migrations.CreateModel(
            name="Bostwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kolejnosc",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order, e.g. 1–12 following the months of the year.",
                    ),
                ),
                ("imie_pl", models.CharField(max_length=80, verbose_name="Name (PL)")),
                ("imie_en", models.CharField(max_length=80, verbose_name="Name (EN)")),
                (
                    "epitet_pl",
                    models.CharField(
                        blank=True,
                        help_text="Short line under the name, e.g. 'Pan przełomu i cieni'.",
                        max_length=160,
                        verbose_name="Epithet / tagline (PL)",
                    ),
                ),
                (
                    "epitet_en",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Epithet / tagline (EN)",
                    ),
                ),
                (
                    "opis_pl",
                    models.TextField(
                        help_text="Longer, narrative description — same storytelling tone as festival sections.",
                        verbose_name="Story (PL)",
                    ),
                ),
                ("opis_en", models.TextField(verbose_name="Story (EN)")),
                (
                    "ciekawostka_pl",
                    models.TextField(
                        blank=True,
                        help_text="Short 'did you know' aside shown in its own box in the panel.",
                        verbose_name="Trivia (PL)",
                    ),
                ),
                (
                    "ciekawostka_en",
                    models.TextField(blank=True, verbose_name="Trivia (EN)"),
                ),
                (
                    "obraz",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=core.storages_backends.get_bies_storage,
                        upload_to="bies/bostwa/",
                        verbose_name="Portrait",
                    ),
                ),
                (
                    "swieta",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Usually just one festival (the month this patron watches over).",
                        related_name="bostwa",
                        to="bies.swieto",
                        verbose_name="Festivals / months",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patron / deity",
                "verbose_name_plural": "Patrons / deities",
                "ordering": ["kolejnosc", "imie_pl"],
            },
        ),
    ]
