# Generated by Django 5.2.14 on 2026-07-09 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bies", "0008_alter_swieto_duchy_en_alter_swieto_duchy_pl_bostwo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bostwo",
            name="swieta",
        ),
        migrations.AddField(
            model_name="bostwo",
            name="swieto",
            field=models.OneToOneField(
                blank=True,
                help_text="The one festival (month) this patron watches over.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bostwo",
                to="bies.swieto",
                verbose_name="Festival / month",
            ),
        ),
    ]
