# Generated by Django 5.2.14 on 2026-07-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bies", "0009_remove_bostwo_swieta_bostwo_swieto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bostwo",
            name="swieto",
        ),
        migrations.AddField(
            model_name="bostwo",
            name="swieta",
            field=models.ManyToManyField(
                blank=True,
                help_text="All festivals this patron covers — usually the 1 or 2 festivals that fall in their month (most months have 2 festivals sharing one patron; only Sieczeń/January has just 1).",
                related_name="bostwa",
                to="bies.swieto",
                verbose_name="Festivals / months",
            ),
        ),
    ]
