# Thin compatibility facade.
# Keep public symbols here so existing imports (`from . import views`) keep working.

from .models import (  # noqa: F401
    Articulator,
    Exercise,
    Funfact,
    OldPolish,
    Trivia,
    Twister,
)
from .views_api import (  # noqa: F401
    ArticulatorViewSet,
    CustomTokenObtainPairView,
    ExerciseViewSet,
    FunfactViewSet,
    HealthCheckView,
    OldPolishViewSet,
    TriviaViewSet,
    TwisterViewSet,
)
from .views_auth import (  # noqa: F401
    activate,
    contact,
    login_view,
    password_reset_complete_view,
    password_reset_confirm_view,
    password_reset_done_view,
    password_reset_view,
    register_view,
    send_activation_email,
)
from .views_crud import (  # noqa: F401
    articulator_add,
    articulator_delete,
    articulator_edit,
    articulator_list,
    exercise_add,
    exercise_delete,
    exercise_edit,
    exercise_list,
    funfact_add,
    funfact_delete,
    funfact_edit,
    funfact_list,
    oldpolish_add,
    oldpolish_delete,
    oldpolish_edit,
    oldpolish_list,
    trivia_add,
    trivia_delete,
    trivia_edit,
    trivia_list,
    twister_add,
    twister_delete,
    twister_edit,
    twister_list,
)
from .views_main import (  # noqa: F401
    add_articulator,
    add_exercise,
    add_twister,
    chatbot,
    content_management,
    delete_articulator,
    delete_exercise,
    delete_twister,
    error_404_view,
    get_chatbot,
    load_more_articulators,
    load_more_exercises,
    load_more_funfacts,
    load_more_old_polish,
    load_more_trivia,
    load_more_twisters,
    main,
    user_content,
)
