# Generated by Django 5.2.17 on 2026-09-29 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walczak", "0002_seed"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumorQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_pl", models.TextField()),
                ("text_en", models.TextField()),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="IPIPScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name_pl", models.CharField(max_length=80)),
                ("name_en", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="PreferenceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_pl", models.TextField()),
                ("text_en", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("scale", "Scale 1–5"),
                            ("ab", "A or B"),
                            ("situation", "Situation"),
                            ("multi", "Several options"),
                        ],
                        max_length=16,
                    ),
                ),
                ("dimension", models.CharField(blank=True, max_length=32)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="StyleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name_pl", models.CharField(max_length=80)),
                ("name_en", models.CharField(max_length=80)),
            ],
            options={
                "ordering": ["name_pl"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name_pl", models.CharField(max_length=80)),
                ("name_en", models.CharField(max_length=80)),
            ],
            options={
                "ordering": ["name_pl"],
            },
        ),
        migrations.AddField(
            model_name="source",
            name="accessed_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="attribution",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="source",
            name="license",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="source",
            name="license_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="source",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="source",
            name="publication_date",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("academic", "Academic"),
                    ("federation", "Federation"),
                    ("historical", "Historical"),
                    ("encyclopedia", "Encyclopedia"),
                    ("wikimedia", "Wikimedia"),
                    ("wikipedia", "Wikipedia / Wikidata"),
                    ("public_domain", "Public domain"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="catalog_set",
            field=models.CharField(
                choices=[("core", "Core"), ("golden", "Golden")],
                default="core",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="competition_status",
            field=models.CharField(
                choices=[
                    ("sport", "Sport competition"),
                    ("traditional", "Traditional practice"),
                    ("both", "Both"),
                    ("none", "Neither"),
                    ("historical", "Historical"),
                ],
                default="both",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="origin_en",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="style",
            name="origin_pl",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="style",
            name="period_en",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="style",
            name="period_pl",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="style",
            name="region",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="style",
            name="sources_disagree",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="style",
            name="weapon_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("optional", "Optional"),
                    ("primary", "Primary"),
                    ("training", "Training weapon"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="walczak.style",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="joke_en",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="Joke (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="joke_pl",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="Joke (PL)"
            ),
        ),
        migrations.CreateModel(
            name="Archetype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name_pl", models.CharField(max_length=120)),
                ("name_en", models.CharField(max_length=120)),
                ("description_pl", models.TextField()),
                ("description_en", models.TextField()),
                (
                    "styles",
                    models.ManyToManyField(
                        blank=True, related_name="archetypes", to="walczak.style"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_pl", models.TextField()),
                ("text_en", models.TextField()),
                ("is_legend", models.BooleanField(default=False)),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True, related_name="facts", to="walczak.source"
                    ),
                ),
                (
                    "styles",
                    models.ManyToManyField(
                        blank=True, related_name="facts", to="walczak.style"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HumorChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_pl", models.CharField(max_length=240)),
                ("text_en", models.CharField(max_length=240)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("points", models.PositiveSmallIntegerField(default=1)),
                (
                    "archetype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="walczak.archetype",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="walczak.humorquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="IPIPItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_en", models.TextField()),
                ("text_pl", models.TextField()),
                ("reverse", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "attribution",
                    models.CharField(
                        default="IPIP public-domain item. Polish wording is a project translation.",
                        max_length=240,
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="walczak.ipipscale",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PreferenceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_pl", models.CharField(max_length=240)),
                ("text_en", models.CharField(max_length=240)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="walczak.preferencequestion",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("population", models.CharField(blank=True, max_length=240)),
                ("design", models.CharField(blank=True, max_length=240)),
                ("finding_pl", models.TextField(blank=True)),
                ("finding_en", models.TextField(blank=True)),
                ("limitation_pl", models.TextField(blank=True)),
                ("limitation_en", models.TextField(blank=True)),
                (
                    "evidence",
                    models.CharField(
                        choices=[
                            ("strong", "Strong"),
                            ("moderate", "Moderate"),
                            ("limited", "Limited"),
                            ("unclear", "Unclear"),
                        ],
                        default="unclear",
                        max_length=16,
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True, related_name="studies", to="walczak.source"
                    ),
                ),
                (
                    "styles",
                    models.ManyToManyField(related_name="studies", to="walczak.style"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="style",
            name="style_types",
            field=models.ManyToManyField(
                blank=True, related_name="styles", to="walczak.styletype"
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="styles", to="walczak.tag"
            ),
        ),
        migrations.CreateModel(
            name="TrainingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "striking",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "grappling",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "clinch",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "throws",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "takedowns",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "ground_fighting",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "submissions",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "punches",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "kicks",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "knees",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "elbows",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "weapons",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "solo_training",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "partner_training",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "contact_level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "competition_level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "tradition_level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "technical_complexity",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "athletic_demand",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "endurance_demand",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "explosiveness",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "equipment_required",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "style",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="walczak.style",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptionWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dimension", models.CharField(max_length=32)),
                ("weight", models.SmallIntegerField()),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="walczak.preferenceoption",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("option", "dimension"), name="uniq_option_dimension"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StyleRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("variant", "Variant"),
                            ("umbrella", "Umbrella"),
                            ("subset", "Subset"),
                            ("related", "Related"),
                            ("influenced", "Influenced"),
                            ("derived_from", "Derived from"),
                            ("historical_precursor", "Historical precursor"),
                            ("modern_form", "Modern form"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note_pl", models.CharField(blank=True, max_length=240)),
                ("note_en", models.CharField(blank=True, max_length=240)),
                (
                    "from_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_out",
                        to="walczak.style",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True, related_name="relations", to="walczak.source"
                    ),
                ),
                (
                    "to_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_in",
                        to="walczak.style",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_style", "to_style", "kind"),
                        name="uniq_style_relation",
                    )
                ],
            },
        ),
    ]
