# Generated by Django 5.2.13 on 2026-10-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walczak', '0007_boxing_copy_refresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humorchoice',
            name='archetype',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='extra_style',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='style',
        ),
        migrations.RemoveField(
            model_name='humorchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='ipipitem',
            name='scale',
        ),
        migrations.DeleteModel(
            name='Archetype',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='HumorChoice',
        ),
        migrations.DeleteModel(
            name='HumorQuestion',
        ),
        migrations.DeleteModel(
            name='IPIPItem',
        ),
        migrations.DeleteModel(
            name='IPIPScale',
        ),
    ]
