"""One-off: emit CORE dict literals from _dump_wiciedzy.json. Not run in CI."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = json.loads((ROOT / "_dump_wiciedzy.json").read_text(encoding="utf-8"))

DIM_ORDER = [
    "striking",
    "grappling",
    "clinch",
    "throws",
    "takedowns",
    "ground_fighting",
    "submissions",
    "punches",
    "kicks",
    "knees",
    "elbows",
    "weapons",
    "solo_training",
    "partner_training",
    "contact_level",
    "competition_level",
    "tradition_level",
    "technical_complexity",
    "athletic_demand",
    "endurance_demand",
    "explosiveness",
    "equipment_required",
]


def q(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def source_line(src: dict) -> str:
    title, url = src["title"], src["url"]
    author = src.get("author", "")
    st = src.get("source_type", "")
    role = src.get("role", "definition")
    quality = src.get("quality", "secondary")
    if st == "wikipedia" or author == "Wikipedia contributors":
        return f'wiki({q(title)}, {q(url)}, role={q(role)}, quality={q(quality)})'
    if st == "encyclopedia" and "Britannica" in author:
        return f'brit({q(title)}, {q(url)}, role={q(role)}, quality={q(quality)})'
    if st == "federation":
        return f'fed({q(title)}, {q(url)}, {q(author)}, role={q(role)}, quality={q(quality)})'
    if quality == "institutional" and "UNESCO" in author:
        return f'src({q(title)}, {q(url)}, {q(author)}, "historical", role={q(role)}, quality={q(quality)})'
    return f'src({q(title)}, {q(url)}, {q(author)}, {q(st)}, role={q(role)}, quality={q(quality)})'


lines: list[str] = []
for row in DATA["styles"]:
    prof = row["profile"]
    pvals = ", ".join(str(prof[k]) for k in DIM_ORDER)
    srcs = ",\n            ".join(source_line(s) for s in row["sources"])
    types = ", ".join(q(t) for t in row["types"])
    block = f"""    {{
        "slug": {q(row["slug"])},
        "sort_order": {row["sort_order"]},
        "family": {q(row["family"])},
        "catalog_set": {q(row["catalog_set"])},
        "name_pl": {q(row["name_pl"])},
        "name_en": {q(row["name_en"])},
        "origin_pl": {q(row["origin_pl"])},
        "origin_en": {q(row["origin_en"])},
        "region": {q(row["region"])},
        "period_pl": {q(row["period_pl"])},
        "period_en": {q(row["period_en"])},
        "competition_status": {q(row["competition_status"])},
        "weapon_status": {q(row["weapon_status"])},
        "types": [{types}],
        "summary_pl": {q(row["summary_pl"])},
        "summary_en": {q(row["summary_en"])},
        "history_pl": {q(row["history_pl"])},
        "history_en": {q(row["history_en"])},
        "practice_pl": {q(row["practice_pl"])},
        "practice_en": {q(row["practice_en"])},
        "profile": P({pvals}),
        "sources": [
            {srcs},
        ],
    }},"""
    lines.append(block)

out = ROOT / "wiciedzy" / "data" / "_core_backfill_fragment.py"
out.write_text("# Generated by wiciedzy/scripts/gen_core_backfill.py\n\nBACKFILL_CORE = [\n" + "\n".join(lines) + "\n]\n", encoding="utf-8")
print("wrote", out)
