# Generated by Django 5.2.13 on 2026-09-26 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "skill",
                    models.CharField(
                        choices=[
                            ("L", "Listening"),
                            ("S", "Speaking"),
                            ("R", "Reading"),
                            ("W", "Writing"),
                        ],
                        max_length=1,
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(default=2)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple choice"),
                            ("listening", "Listening"),
                            ("speaking", "Speaking"),
                            ("writing", "Writing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expected_minutes", models.PositiveSmallIntegerField(default=7)),
                ("original_content", models.BooleanField(default=True)),
                (
                    "source_note",
                    models.CharField(
                        default="Original Poligon content", max_length=220
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "title_pl",
                    models.CharField(max_length=180, verbose_name="Title (PL)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=180, verbose_name="Title (EN)"),
                ),
                ("instructions_pl", models.TextField(verbose_name="Instructions (PL)")),
                ("instructions_en", models.TextField(verbose_name="Instructions (EN)")),
                ("prompt_pl", models.TextField(verbose_name="Prompt (PL)")),
                ("prompt_en", models.TextField(verbose_name="Prompt (EN)")),
                (
                    "content_pl",
                    models.TextField(blank=True, verbose_name="Content (PL)"),
                ),
                (
                    "content_en",
                    models.TextField(blank=True, verbose_name="Content (EN)"),
                ),
                (
                    "category_pl",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Category (PL)"
                    ),
                ),
                (
                    "category_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Category (EN)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LearnerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=64, unique=True)),
                ("target_profile", models.CharField(default="2222", max_length=8)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("daily_minutes", models.PositiveIntegerField(default=35)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Learner state",
                "verbose_name_plural": "Learner states",
            },
        ),
        migrations.CreateModel(
            name="StudyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=64)),
                ("skill", models.CharField(max_length=1)),
                ("minutes", models.PositiveSmallIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Study event",
                "verbose_name_plural": "Study events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VocabularyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=120, unique=True)),
                ("translation", models.CharField(max_length=180)),
                ("explanation_pl", models.TextField(verbose_name="Explanation (PL)")),
                ("explanation_en", models.TextField(verbose_name="Explanation (EN)")),
                ("example_pl", models.TextField(verbose_name="Example (PL)")),
                ("example_en", models.TextField(verbose_name="Example (EN)")),
                (
                    "category_pl",
                    models.CharField(
                        default="ogólny", max_length=80, verbose_name="Category (PL)"
                    ),
                ),
                (
                    "category_en",
                    models.CharField(
                        default="general", max_length=80, verbose_name="Category (EN)"
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(default=2)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Vocabulary item",
                "verbose_name_plural": "Vocabulary items",
                "ordering": ["term"],
            },
        ),
        migrations.CreateModel(
            name="ChoiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_pl", models.CharField(max_length=300, verbose_name="Text (PL)")),
                ("text_en", models.CharField(max_length=300, verbose_name="Text (EN)")),
                ("is_correct", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="poligon.exercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Choice option",
                "verbose_name_plural": "Choice options",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=64)),
                ("answer_text", models.TextField(blank=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("feedback", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poligon.exercise",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="poligon.choiceoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=64)),
                ("due_at", models.DateTimeField()),
                ("interval_days", models.PositiveIntegerField(default=0)),
                ("ease", models.FloatField(default=2.5)),
                ("repetitions", models.PositiveIntegerField(default=0)),
                ("last_grade", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poligon.vocabularyitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["due_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session_key", "item"),
                        name="poligon_review_session_item_uniq",
                    )
                ],
            },
        ),
    ]
