# Generated by Django 5.2.13 on 2026-09-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poligon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabularyitem",
            name="attribution_en",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="vocabularyitem",
            name="attribution_pl",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="vocabularyitem",
            name="content_source",
            field=models.CharField(
                choices=[
                    ("original", "Original"),
                    ("wiktionary", "Wiktionary"),
                    ("wikidata", "Wikidata"),
                ],
                default="original",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vocabularyitem",
            name="retrieved_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vocabularyitem",
            name="source_license",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="vocabularyitem",
            name="source_url",
            field=models.URLField(blank=True),
        ),
    ]
