# Generated by Django 5.2.13 on 2026-09-26 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poligon", "0002_vocabulary_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="attribution_en",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="exercise",
            name="attribution_pl",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="exercise",
            name="content_source",
            field=models.CharField(
                choices=[
                    ("original", "Original"),
                    ("wiktionary", "Wiktionary"),
                    ("wikipedia", "Wikipedia"),
                    ("tatoeba", "Tatoeba"),
                    ("wikidata", "Wikidata"),
                ],
                default="original",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="retrieved_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="source_license",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="exercise",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="learnerstate",
            name="practice_level",
            field=models.PositiveSmallIntegerField(
                default=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vocabularyitem",
            name="content_source",
            field=models.CharField(
                choices=[
                    ("original", "Original"),
                    ("wiktionary", "Wiktionary"),
                    ("wikipedia", "Wikipedia"),
                    ("tatoeba", "Tatoeba"),
                    ("wikidata", "Wikidata"),
                ],
                default="original",
                max_length=20,
            ),
        ),
    ]
