# Generated by Django 5.2.17 on 2026-09-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poligon", "0004_learner_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="explanation_en",
            field=models.TextField(blank=True, verbose_name="Why (EN)"),
        ),
        migrations.AddField(
            model_name="exercise",
            name="explanation_pl",
            field=models.TextField(blank=True, verbose_name="Why (PL)"),
        ),
    ]
