# Generated by Django 5.2.17 on 2026-10-01 18:16

import json
from pathlib import Path

from django.db import migrations, models

ACTIVE_SLUGS_PATH = Path(__file__).resolve().parents[1] / "data" / "active_slugs.json"


def mark_the_live_queue(apps, schema_editor):
    """The allowlist is the queue that already shipped. New publishes come from JSON."""
    exercise = apps.get_model("poligon", "Exercise")
    keep = set(json.loads(ACTIVE_SLUGS_PATH.read_text(encoding="utf-8")))
    exercise.objects.filter(slug__in=keep).update(
        publication_status="published",
        quality_status="legacy",
        active=True,
    )
    exercise.objects.exclude(slug__in=keep).update(publication_status="draft", active=False)
    exercise.objects.filter(content_source="original").update(source_type="original")
    exercise.objects.exclude(content_source="original").update(source_type="external")


class Migration(migrations.Migration):

    dependencies = [
        ("poligon", "0009_five_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="competency",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="exercise",
            name="learning_objective",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="exercise",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("review", "review"),
                    ("approved", "approved"),
                    ("published", "published"),
                    ("deprecated", "deprecated"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="quality_status",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="exercise",
            name="review_status",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="exercise",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="reviewed_by",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="exercise",
            name="scenario",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="exercise",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("original", "original"),
                    ("external", "external"),
                    ("adapted", "adapted"),
                    ("generated", "generated"),
                ],
                default="original",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="subskill",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="exercise",
            name="success_criteria",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="vocabularyitem",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("review", "review"),
                    ("approved", "approved"),
                    ("published", "published"),
                    ("deprecated", "deprecated"),
                ],
                default="published",
                max_length=16,
            ),
        ),
        migrations.RunPython(mark_the_live_queue, migrations.RunPython.noop),
    ]
