# Generated by Django 5.2.17 on 2026-10-01 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poligon", "0010_content_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="catalog_role",
            field=models.CharField(
                choices=[("practice", "practice"), ("placement", "placement")],
                default="practice",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="PlacementAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm_version",
                    models.CharField(default="placement_v1", max_length=32),
                ),
                ("correct_count", models.PositiveSmallIntegerField()),
                ("question_count", models.PositiveSmallIntegerField()),
                ("suggested_level", models.PositiveSmallIntegerField()),
                ("answers", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_attempts",
                        to="poligon.learnerstate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Placement attempt",
                "verbose_name_plural": "Placement attempts",
                "ordering": ["-created_at"],
            },
        ),
    ]
