# Generated by Django 5.2.13 on 2026-05-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rugby", "0002_post_bilingual"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["published_date"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="text_pl",
            field=models.TextField(verbose_name="Treść (PL)"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title_pl",
            field=models.CharField(max_length=255, verbose_name="Tytuł (PL)"),
        ),
    ]
